[tool.poetry]
name = "hkari_musicbot_banner"
version = "1.0"
description = "Python dependency management and packaging made easy."
authors = ["LEv145"]


[tool.poetry.dependencies]
python = "^2.7"


[tool.poetry.scripts]
poetry = "poetry.console.application:main"
