[tool.poetry]
name = "hikari_musicbot_banner"
version = "1.0"
description = "Python dependency management and packaging made easy."
authors = ["LEv145"]
include = ["banner.txt"]


[tool.poetry.dependencies]
python = "^2.7"
